### ISSUE TITLE
Transforms not showing up in task inspector

### ISSUE THREAD

**Issue by dmronga** [rock-core/gui-vizkit#27]
Hi,

on master branch, the transformer frames are not displayed in the task inspector anymore. When I go back to commit bf26f3abb9ebb58971e0224a998b46fb9608f6ea, the transforms are displayed properly again.

I am using the following scripts to generate transforms and start the transformer.

#######################################################################

#Generate a transform:

require 'orocos'
Orocos.initialize
Orocos.load_typekit('base')

task = Orocos::RubyTaskContext.new "task_a"
p=task.create_output_port('tr_out', Types::Base::Samples::RigidBodyState)
task.configure
task.start
while true
    sample = Types::Base::Samples::RigidBodyState.new
    sample.position = Types::Base::Vector3d.new(1,5,3)
    sample.orientation = Types::Base::Quaterniond.from_angle_axis(0.14,Types::Base::Vector3d.new(1,0,0))
    sample.sourceFrame = "O"
    sample.targetFrame = "A"
    sample.time=Types::Base::Time.now
   
    p.write(sample)
    sleep(0.1)
end

task.stop
task.dispose

#######################################################################

#Start the transformer:

require 'orocos'
require 'transformer/runtime'

Orocos.initialize
Orocos.transformer.load_conf('transforms.rb')

Orocos.transformer.manager.conf.dynamic_transform "task_a.tr_out","O" => "A"

Orocos.transformer.update_configuration_state

Orocos.run Transformer.broadcaster_name do
    bc=Orocos.name_service.get(Transformer.broadcaster_name)
    bc.start
    sleep(1)
    bc.setConfiguration Orocos.transformer.configuration_state
    STDIN.readline
end

#######################################################################

#transforms.rb file:

dynamic_transform "task_a.tr_out",
      "O" => "A"

#######################################################################

I am trying to display the transforms by right clicking on the configuration_state port of the transformer_broadcaster in the task inspector and using Vizkit3DWidget. I am on Ubuntu 14.04. 

Best,
Dennis

**Comment by D-Alex** [comment]
should be fixed on master - please reopen if you still encounter problems

**Comment by goldhoorn** [comment]
On the mailinglist was a discussion that the problem still exists:
@dmronga @skasperski can someone of you a minimal example which is failing?
(e.g. rock script or examplary rock-task?)

**Comment by goldhoorn** [comment]
When running: 
/home/goldhoorn/bootstraps/master/gui/vizkit3d/scripts/show.rb

are the transformations are shown?

Whats the state for the release?

**Comment by dmronga** [comment]
Can you attach the script, please?

**Comment by goldhoorn** [comment]
it's normally installed in your vizkit3d repro

**Comment by dmronga** [comment]
Ah, ok! Yes these transforms are showing up.

**Comment by goldhoorn** [comment]
@D-Alex

**Comment by goldhoorn** [comment]
@dmronga if i following your steps and example scritps from above i get a crash from ruby:
(which should not happen too)

```
ruby2.1: /home/goldhoorn/bootstraps/master/gui/vizkit3d/src/Vizkit3DWidget.cpp:695: void vizkit3d::Vizkit3DWidget::addPluginIntern(QObject*, QObject*): Zusicherung »plugin« nicht erfüllt.
Abgebrochen
```

**Comment by dmronga** [comment]
Hmm, on my machine the scripts work. Different ruby version!? I have 2.0

**Comment by D-Alex** [comment]
I tried dmronga's script and all transformations are showing up. The relevant fix has the following commit id df9edd9f2da7439b898cd9d9bc0c17d23b2c8fcf. Are you using the latest release?

**Comment by dmronga** [comment]
Seems like I really didn't have the correct version. After this commit it is working for me.

**Comment by skasperski** [comment]
I tried to create a minimal example for this issue, but run into a probably different issue, which I posted here: https://github.com/rock-core/tools-orocosrb/issues/71

**Comment by skasperski** [comment]
After resolving the previous issue, I now made the minimal example, which is to be found here:
git@git.hb.dfki.de:skasperski/test-transformer.git

Test using "scripts/start.rb"

The transformation is published correctly (as seen by visualizing the RigidBodyState "source2target", but no transformation is available)
