### ISSUE TITLE
StructViewer not showing prepending 0 in millisecond part of time value

### ISSUE THREAD

**Issue by christian-rauch** [rock-core/gui-vizkit#3]
The StructViewer (inside rock-replay) is not showing the prepeding 0 from a millisecond value of a timestamp.

E.g.: The StructViewer will show "22 Jul 2014 11:47:23.34781" for a time field while calling toString() for the same sample inside the updateHook will give "20140722-11:47:23:034781".
The '0' form "034781" is missing in the StructViewer.

**Comment by goldhoorn** [comment]
@christian-rauch is this issue still valid?

**Comment by christian-rauch** [comment]
I didn't test this recently. If there was no patch to fix this, I guess it is still valid.

**Comment by goldhoorn** [comment]
On 08.06.2015 13:30, Christian Rauch wrote:
>
> I didn't test this recently. If there was no patch to fix this, I 
> guess it is still valid.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/rock-core/gui-vizkit/issues/3#issuecomment-109957222>.
>
We moved on with the ruby version, please can you recheck?

-- 
  Dipl.-Inf. Matthias Goldhoorn
  Space and Underwater Robotic

  Universität Bremen
  FB 3 - Mathematik und Informatik
  AG Robotik
  Robert-Hooke-Straße 1
  28359 Bremen, Germany
  
  Zentrale: +49 421 178 45-6611
  
  Besuchsadresse der Nebengeschäftstelle:
  Robert-Hooke-Straße 5
  28359 Bremen, Germany
  
  Tel.:    +49 421 178 45-4193
  Empfang: +49 421 178 45-6600
  Fax:     +49 421 178 45-4150
  E-Mail:  matthias.goldhoorn@informatik.uni-bremen.de

  Weitere Informationen: http://www.informatik.uni-bremen.de/robotik

**Comment by christian-rauch** [comment]
The bug still exists. I think this problem is unrelated to the ruby version but is caused by some conversion of the milliseconds to integer internally, where the trailing 0 is removed.

**Comment by goldhoorn** [comment]
@D-Alex yould you please fix this its mos probably a bug here:
https://github.com/rock-core/gui-vizkit/blob/master/lib/vizkit/vizkit_items.rb#L231

**Comment by goldhoorn** [comment]
Should be fixed by: https://github.com/rock-core/gui-vizkit/pull/41
(please continue discussion there)
